CREATE SCHEMA IF NOT EXISTS orders;

CREATE TABLE orders.trade_order (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account       TEXT   NOT NULL,
    symbol        TEXT   NOT NULL,
    side          TEXT   NOT NULL,
    price         BIGINT NOT NULL,   -- paise
    quantity      BIGINT NOT NULL,
    filled_qty    BIGINT NOT NULL DEFAULT 0,
    status        TEXT   NOT NULL,
    reject_reason TEXT,
    version       BIGINT NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE orders.idempotency (
    key        TEXT PRIMARY KEY,
    order_id   BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE orders.audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT NOT NULL,
    account     TEXT   NOT NULL,
    action      TEXT   NOT NULL,
    principal   TEXT   NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    detail      TEXT
);

CREATE TABLE orders.applied_trade (
    event_id   UUID PRIMARY KEY,
    order_id   BIGINT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE orders.instrument (
    symbol TEXT PRIMARY KEY,
    name   TEXT NOT NULL
);

INSERT INTO orders.instrument (symbol, name) VALUES
    ('ACME', 'Acme Corp'),
    ('INFY', 'Infosys Ltd');
