CREATE SCHEMA IF NOT EXISTS ledger;

CREATE TABLE ledger.posting (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txn_id     UUID   NOT NULL,
    account    TEXT   NOT NULL,
    amount     BIGINT NOT NULL,   -- signed paise
    kind       TEXT   NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ledger_posting_account_idx ON ledger.posting (account);

CREATE TABLE ledger.processed_event (
    event_id     UUID PRIMARY KEY,
    processed_at TIMESTAMPTZ NOT NULL
);

-- Opening deposits, balanced per txn: credit each trader, debit the house capital account.
INSERT INTO ledger.posting (txn_id, account, amount, kind) VALUES
    ('00000000-0000-0000-0000-000000000001', 'trader1',  100000000, 'OPENING'),
    ('00000000-0000-0000-0000-000000000001', 'house',   -100000000, 'OPENING'),
    ('00000000-0000-0000-0000-000000000002', 'trader2',  100000000, 'OPENING'),
    ('00000000-0000-0000-0000-000000000002', 'house',   -100000000, 'OPENING');
